package ca.etsmtl.log720.lab3.objetsDonnees;

// Generated 2014-11-29 16:03:21 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DossierInfraction generated by hbm2java
 */
@Entity
@Table(name = "dossier_infraction", schema = "public")
public class DossierInfraction implements java.io.Serializable {

	private int id;
	private Infraction infraction;
	private Dossier dossier;

	public DossierInfraction() {
	}

	public DossierInfraction(int id, Infraction infraction, Dossier dossier) {
		this.id = id;
		this.infraction = infraction;
		this.dossier = dossier;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "infraction_id", nullable = false)
	public Infraction getInfraction() {
		return this.infraction;
	}

	public void setInfraction(Infraction infraction) {
		this.infraction = infraction;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dossier_id", nullable = false)
	public Dossier getDossier() {
		return this.dossier;
	}

	public void setDossier(Dossier dossier) {
		this.dossier = dossier;
	}

}
