package ca.etsmtl.log720.lab3.objetsDonnees;

// Generated 2014-11-29 16:03:21 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Dossier generated by hbm2java
 */
@Entity
@Table(name = "dossier", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "numeropermis"))
public class Dossier implements java.io.Serializable {

	private int id;
	private String nom;
	private String prenom;
	private String numeroplaque;
	private String numeropermis;
	private Set<DossierInfraction> dossierInfractions = new HashSet<DossierInfraction>(
			0);

	public Dossier() {
	}

	public Dossier(int id) {
		this.id = id;
	}

	public Dossier(int id, String nom, String prenom, String numeroplaque,
			String numeropermis, Set<DossierInfraction> dossierInfractions) {
		this.id = id;
		this.nom = nom;
		this.prenom = prenom;
		this.numeroplaque = numeroplaque;
		this.numeropermis = numeropermis;
		this.dossierInfractions = dossierInfractions;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "nom", length = 100)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "prenom", length = 100)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "numeroplaque", length = 50)
	public String getNumeroplaque() {
		return this.numeroplaque;
	}

	public void setNumeroplaque(String numeroplaque) {
		this.numeroplaque = numeroplaque;
	}

	@Column(name = "numeropermis", unique = true, length = 50)
	public String getNumeropermis() {
		return this.numeropermis;
	}

	public void setNumeropermis(String numeropermis) {
		this.numeropermis = numeropermis;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dossier")
	public Set<DossierInfraction> getDossierInfractions() {
		return this.dossierInfractions;
	}

	public void setDossierInfractions(Set<DossierInfraction> dossierInfractions) {
		this.dossierInfractions = dossierInfractions;
	}

}
