package ca.etsmtl.log720.lab3.objetsDonnees;

// Generated 2014-12-01 02:55:37 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Dossier generated by hbm2java
 */
public class Dossier implements java.io.Serializable {

	private int id;
	private String nom;
	private String prenom;
	private String numeroplaque;
	private String numeropermis;
	private Set dossierInfractions = new HashSet(0);

	public Dossier() {
	}

	public Dossier(int id) {
		this.id = id;
	}

	public Dossier(int id, String nom, String prenom, String numeroplaque,
			String numeropermis, Set dossierInfractions) {
		this.id = id;
		this.nom = nom;
		this.prenom = prenom;
		this.numeroplaque = numeroplaque;
		this.numeropermis = numeropermis;
		this.dossierInfractions = dossierInfractions;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public String getNumeroplaque() {
		return this.numeroplaque;
	}

	public void setNumeroplaque(String numeroplaque) {
		this.numeroplaque = numeroplaque;
	}

	public String getNumeropermis() {
		return this.numeropermis;
	}

	public void setNumeropermis(String numeropermis) {
		this.numeropermis = numeropermis;
	}

	public Set getDossierInfractions() {
		return this.dossierInfractions;
	}

	public void setDossierInfractions(Set dossierInfractions) {
		this.dossierInfractions = dossierInfractions;
	}

}
