package ca.etsmtl.log720.lab3.objetsDonnees;

// Generated 2014-12-01 02:55:37 by Hibernate Tools 4.3.1

/**
 * DossierInfraction generated by hbm2java
 */
public class DossierInfraction implements java.io.Serializable {

	private int id;
	private Dossier dossier;
	private Infraction infraction;

	public DossierInfraction() {
	}

	public DossierInfraction(int id, Dossier dossier, Infraction infraction) {
		this.id = id;
		this.dossier = dossier;
		this.infraction = infraction;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Dossier getDossier() {
		return this.dossier;
	}

	public void setDossier(Dossier dossier) {
		this.dossier = dossier;
	}

	public Infraction getInfraction() {
		return this.infraction;
	}

	public void setInfraction(Infraction infraction) {
		this.infraction = infraction;
	}

}
