package ca.etsmtl.log720.lab3.objetsDonnees;

// Generated 2014-12-07 10:24:11 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Infraction generated by hbm2java
 */
public class Infraction implements java.io.Serializable {

	private int id;
	private Integer niveaugravite;
	private String description;
	private Set dossierInfractions = new HashSet(0);

	public Infraction() {
	}

	public Infraction(int id) {
		this.id = id;
	}

	public Infraction(int id, Integer niveaugravite, String description,
			Set dossierInfractions) {
		this.id = id;
		this.niveaugravite = niveaugravite;
		this.description = description;
		this.dossierInfractions = dossierInfractions;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getNiveaugravite() {
		return this.niveaugravite;
	}

	public void setNiveaugravite(Integer niveaugravite) {
		this.niveaugravite = niveaugravite;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getDossierInfractions() {
		return this.dossierInfractions;
	}

	public void setDossierInfractions(Set dossierInfractions) {
		this.dossierInfractions = dossierInfractions;
	}

}
