package ca.etsmtl.log720.lab3.objetsDonnees;

// Generated 2014-11-29 16:03:21 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Infraction generated by hbm2java
 */
@Entity
@Table(name = "infraction", schema = "public")
public class Infraction implements java.io.Serializable {

	private int id;
	private Integer niveaugravite;
	private String description;
	private Set<DossierInfraction> dossierInfractions = new HashSet<DossierInfraction>(
			0);

	public Infraction() {
	}

	public Infraction(int id) {
		this.id = id;
	}

	public Infraction(int id, Integer niveaugravite, String description,
			Set<DossierInfraction> dossierInfractions) {
		this.id = id;
		this.niveaugravite = niveaugravite;
		this.description = description;
		this.dossierInfractions = dossierInfractions;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "niveaugravite")
	public Integer getNiveaugravite() {
		return this.niveaugravite;
	}

	public void setNiveaugravite(Integer niveaugravite) {
		this.niveaugravite = niveaugravite;
	}

	@Column(name = "description", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "infraction")
	public Set<DossierInfraction> getDossierInfractions() {
		return this.dossierInfractions;
	}

	public void setDossierInfractions(Set<DossierInfraction> dossierInfractions) {
		this.dossierInfractions = dossierInfractions;
	}

}
