package ca.etsmtl.log720.lab3.objetsDonnees;

// Generated 2014-11-29 16:03:21 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Utilisateur generated by hbm2java
 */
@Entity
@Table(name = "utilisateur", schema = "public")
public class Utilisateur implements java.io.Serializable {

	private int id;
	private Role role;
	private Serializable login;
	private Serializable password;

	public Utilisateur() {
	}

	public Utilisateur(int id) {
		this.id = id;
	}

	public Utilisateur(int id, Role role, Serializable login,
			Serializable password) {
		this.id = id;
		this.role = role;
		this.login = login;
		this.password = password;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "roleid")
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@Column(name = "login")
	public Serializable getLogin() {
		return this.login;
	}

	public void setLogin(Serializable login) {
		this.login = login;
	}

	@Column(name = "password")
	public Serializable getPassword() {
		return this.password;
	}

	public void setPassword(Serializable password) {
		this.password = password;
	}

}
