package ca.etsmtl.log720.lab3.objetsDonnees;

// Generated 2014-12-07 10:24:11 by Hibernate Tools 4.3.1

/**
 * Utilisateur generated by hbm2java
 */
public class Utilisateur implements java.io.Serializable {

	private int id;
	private Role role;
	private String login;
	private String userpassword;

	public Utilisateur() {
	}

	public Utilisateur(int id) {
		this.id = id;
	}

	public Utilisateur(int id, Role role, String login, String userpassword) {
		this.id = id;
		this.role = role;
		this.login = login;
		this.userpassword = userpassword;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getUserpassword() {
		return this.userpassword;
	}

	public void setUserpassword(String userpassword) {
		this.userpassword = userpassword;
	}

}
