package ca.etsmtl.log720.lab3.objetsDonnees;

// Generated 2014-12-01 14:41:34 by Hibernate Tools 4.3.1

import java.io.Serializable;

/**
 * Utilisateur generated by hbm2java
 */
public class Utilisateur implements java.io.Serializable {

	private int id;
	private Role role;
	private Serializable login;
	private Serializable password;

	public Utilisateur() {
	}

	public Utilisateur(int id) {
		this.id = id;
	}

	public Utilisateur(int id, Role role, Serializable login,
			Serializable password) {
		this.id = id;
		this.role = role;
		this.login = login;
		this.password = password;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public Serializable getLogin() {
		return this.login;
	}

	public void setLogin(Serializable login) {
		this.login = login;
	}

	public Serializable getPassword() {
		return this.password;
	}

	public void setPassword(Serializable password) {
		this.password = password;
	}

}
